<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "easyquiz"
 *
 * Auto generated by Extension Builder 2017-03-08
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Easy Quiz',
	'description' => 'Frontend quiz, allowing for multiple questions.',
	'category' => 'plugin',
	'author' => 'Christopher Zechendorf',
	'author_email' => 'christopher@zechendorf.com',
	'state' => 'stable',
	'internal' => '',
	'uploadfolder' => '1',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '1.0.2',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2.0-8.99.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);
